### ISSUE TITLE
Improve join feature

### ISSUE THREAD

**Issue by CharlonTank** [fractal6/fractal6-ui.elm#5]
Hello!

When I tried the app, first thing I notice was this welcoming green button:

![image](https://user-images.githubusercontent.com/4601603/205910708-591cb4d7-7abc-42b8-bccc-a211c027d3f0.png)
When clicking on it:
![image](https://user-images.githubusercontent.com/4601603/205910487-b94e6248-6d75-451f-8779-9cbb4502293f.png)

It would be nice to explain what a tension is and also add a button to join the organisation instead of telling to do it with a warning message

What do you think?
I love this project!

**Comment by dtrckd** [comment]
Hey @CharlonTank 

Thanks for your interest, I like to see people liking it :) 

> What a tension is ? 

Atm , there are two inputs that tries to help users with the terminology
1. the help button in the top navbar
2. the doc, at https://doc.fractale.co linked in the footpage

Please, do not hesitate to share what you think could improve the clarity of this. 

I agree, it could be nice/better to have an action inviting the user to join along the warning.
Note this is an ongoing **tension**.  About proposing relevant actions instead of just a warning/auth message, in general  ;) 
https://fractale.co/tension/f6/0x33e78d

We are working on it.

**Comment by dtrckd** [comment]
This has been fixed in the v0.7.2

There is now a link to the documentation that explain what a tension is + a **Join** button according to the organization settings.

![image](https://user-images.githubusercontent.com/8218696/210158013-8596476d-70ae-48e9-8413-f0ada150e498.png)
